name: keithley_labtools
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - pip
  - setuptools<81
  - numpy
  - scipy
  - pandas
  - matplotlib
  - pyqt=5
  - qcodes>=0.38
  - pyvisa
  - pyvisa-py
  - pyserial
  - pyyaml
